RGBLIGHT_ENABLE = yes

OLED_ENABLE = yes

VIA_ENABLE = yes

COMBO_ENABLE = yes
COMBO_TERM = 100

MUSIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
EXTRAKEY_ENABLE = no
COMMAND_ENABLE = no

CAPS_WORD_ENABLE = yes
# test windows git-pushing skill